export const countryPhoneLengths = [
  { code: "AD", name: "Andorra", dial_code: "+376", phoneLength: 6 },
  {
    code: "AE",
    name: "United Arab Emirates",
    dial_code: "+971",
    phoneLength: 9,
  },
  { code: "AF", name: "Afghanistan", dial_code: "+93", phoneLength: 9 },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    dial_code: "+1-268",
    phoneLength: 10,
  },
  { code: "AI", name: "Anguilla", dial_code: "+1-264", phoneLength: 10 },
  { code: "AL", name: "Albania", dial_code: "+355", phoneLength: 9 },
  { code: "AM", name: "Armenia", dial_code: "+374", phoneLength: 8 },
  { code: "AO", name: "Angola", dial_code: "+244", phoneLength: 9 },
  { code: "AR", name: "Argentina", dial_code: "+54", phoneLength: [10, 11] },
  { code: "AS", name: "American Samoa", dial_code: "+1-684", phoneLength: 10 },
  { code: "AT", name: "Austria", dial_code: "+43", phoneLength: [10, 11] },
  { code: "AU", name: "Australia", dial_code: "+61", phoneLength: 9 },
  { code: "AW", name: "Aruba", dial_code: "+297", phoneLength: 7 },
  { code: "AZ", name: "Azerbaijan", dial_code: "+994", phoneLength: 9 },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    phoneLength: 8,
  },
  { code: "BB", name: "Barbados", dial_code: "+1-246", phoneLength: 10 },
  { code: "BD", name: "Bangladesh", dial_code: "+880", phoneLength: 10 },
  { code: "BE", name: "Belgium", dial_code: "+32", phoneLength: 9 },
  { code: "BF", name: "Burkina Faso", dial_code: "+226", phoneLength: 8 },
  { code: "BG", name: "Bulgaria", dial_code: "+359", phoneLength: 9 },
  { code: "BH", name: "Bahrain", dial_code: "+973", phoneLength: 8 },
  { code: "BI", name: "Burundi", dial_code: "+257", phoneLength: 8 },
  { code: "BJ", name: "Benin", dial_code: "+229", phoneLength: 10 },
  { code: "BN", name: "Brunei Darussalam", dial_code: "+673", phoneLength: 7 },
  { code: "BO", name: "Bolivia", dial_code: "+591", phoneLength: 9 },
  { code: "BR", name: "Brazil", dial_code: "+55", phoneLength: 11 },
  { code: "BS", name: "Bahamas", dial_code: "+1-242", phoneLength: 10 },
  { code: "BT", name: "Bhutan", dial_code: "+975", phoneLength: 7 },
  { code: "BW", name: "Botswana", dial_code: "+267", phoneLength: 7 },
  { code: "BY", name: "Belarus", dial_code: "+375", phoneLength: 9 },
  { code: "BZ", name: "Belize", dial_code: "+501", phoneLength: 7 },
  { code: "CA", name: "Canada", dial_code: "+1", phoneLength: 10 },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    dial_code: "+243",
    phoneLength: 9,
  },
  {
    code: "CF",
    name: "Central African Republic",
    dial_code: "+236",
    phoneLength: 8,
  },
  {
    code: "CG",
    name: "Congo, Republic of the",
    dial_code: "+242",
    phoneLength: 9,
  },
  { code: "CH", name: "Switzerland", dial_code: "+41", phoneLength: 9 },
  { code: "CI", name: "Côte d'Ivoire", dial_code: "+225", phoneLength: 10 },
  { code: "CK", name: "Cook Islands", dial_code: "+682", phoneLength: 5 },
  { code: "CL", name: "Chile", dial_code: "+56", phoneLength: 9 },
  { code: "CM", name: "Cameroon", dial_code: "+237", phoneLength: 9 },
  { code: "CN", name: "China", dial_code: "+86", phoneLength: 11 },
  { code: "CO", name: "Colombia", dial_code: "+57", phoneLength: 10 },
  { code: "CR", name: "Costa Rica", dial_code: "+506", phoneLength: 8 },
  { code: "CU", name: "Cuba", dial_code: "+53", phoneLength: 8 },
  { code: "CV", name: "Cape Verde", dial_code: "+238", phoneLength: 7 },
  { code: "CY", name: "Cyprus", dial_code: "+357", phoneLength: 8 },
  { code: "CZ", name: "Czech Republic", dial_code: "+420", phoneLength: 9 },
  { code: "DE", name: "Germany", dial_code: "+49", phoneLength: 10 },
  { code: "DK", name: "Denmark", dial_code: "+45", phoneLength: 8 },
  {
    code: "DO",
    name: "Dominican Republic",
    dial_code: "+1-809",
    phoneLength: 10,
  },
  { code: "DZ", name: "Algeria", dial_code: "+213", phoneLength: 9 },
  { code: "EC", name: "Ecuador", dial_code: "+593", phoneLength: 9 },
  { code: "EE", name: "Estonia", dial_code: "+372", phoneLength: 8 },
  { code: "EG", name: "Egypt", dial_code: "+20", phoneLength: 10 },
  { code: "ES", name: "Spain", dial_code: "+34", phoneLength: 9 },
  { code: "ET", name: "Ethiopia", dial_code: "+251", phoneLength: 9 },
  { code: "FI", name: "Finland", dial_code: "+358", phoneLength: [9, 10, 11] },
  { code: "FJ", name: "Fiji", dial_code: "+679", phoneLength: 7 },
  { code: "FR", name: "France", dial_code: "+33", phoneLength: 9 },
  { code: "GA", name: "Gabon", dial_code: "+241", phoneLength: 9 },
  { code: "GB", name: "United Kingdom", dial_code: "+44", phoneLength: 10 },
  { code: "GH", name: "Ghana", dial_code: "+233", phoneLength: 9 },
  { code: "GI", name: "Gibraltar", dial_code: "+350", phoneLength: 8 },
  { code: "GL", name: "Greenland", dial_code: "+299", phoneLength: 6 },
  { code: "GM", name: "Gambia", dial_code: "+220", phoneLength: 7 },
  { code: "GN", name: "Guinea", dial_code: "+224", phoneLength: 9 },
  { code: "GP", name: "Guadeloupe", dial_code: "+590", phoneLength: 9 },
  { code: "GQ", name: "Equatorial Guinea", dial_code: "+240", phoneLength: 9 },
  { code: "GR", name: "Greece", dial_code: "+30", phoneLength: 10 },
  { code: "GT", name: "Guatemala", dial_code: "+502", phoneLength: 8 },
  { code: "GU", name: "Guam", dial_code: "+1-671", phoneLength: 10 },
  { code: "GW", name: "Guinea-Bissau", dial_code: "+245", phoneLength: 7 },
  { code: "GY", name: "Guyana", dial_code: "+592", phoneLength: 7 },
  { code: "HK", name: "Hong Kong", dial_code: "+852", phoneLength: 8 },
  { code: "HN", name: "Honduras", dial_code: "+504", phoneLength: 8 },
  { code: "HR", name: "Croatia", dial_code: "+385", phoneLength: 9 },
  { code: "HT", name: "Haiti", dial_code: "+509", phoneLength: 8 },
  { code: "HU", name: "Hungary", dial_code: "+36", phoneLength: [8, 9] },
  { code: "ID", name: "Indonesia", dial_code: "+62", phoneLength: [9, 10, 11, 12] },
  { code: "IE", name: "Ireland", dial_code: "+353", phoneLength: 9 },
  { code: "IL", name: "Israel", dial_code: "+972", phoneLength: 9 },
  { code: "IN", name: "India", dial_code: "+91", phoneLength: 10 },
  { code: "IQ", name: "Iraq", dial_code: "+964", phoneLength: 10 },
  { code: "IR", name: "Iran", dial_code: "+98", phoneLength: 11 },
  { code: "IS", name: "Iceland", dial_code: "+354", phoneLength: 7 },
  { code: "IT", name: "Italy", dial_code: "+39", phoneLength: 10 },
  { code: "JO", name: "Jordan", dial_code: "+962", phoneLength: [8, 9] },
  { code: "KE", name: "Kenya", dial_code: "+254", phoneLength: 10 },
  { code: "KG", name: "Kyrgyzstan", dial_code: "+996", phoneLength: 9 },
  { code: "KH", name: "Cambodia", dial_code: "+855", phoneLength: 9 },
  { code: "KI", name: "Kiribati", dial_code: "+686", phoneLength: 8 },
  { code: "KM", name: "Comoros", dial_code: "+269", phoneLength: 7 },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    dial_code: "+1-869",
    phoneLength: 10,
  },
  {
    code: "KP",
    name: "North Korea",
    dial_code: "+850",
    phoneLength: [6, 7, 13],
  },
  { code: "KR", name: "South Korea", dial_code: "+82", phoneLength: [8, 9, 10] },
  { code: "KW", name: "Kuwait", dial_code: "+965", phoneLength: 8 },
  { code: "KY", name: "Cayman Islands", dial_code: "+1-345", phoneLength: 7 },
  { code: "LB", name: "Lebanon", dial_code: "+961", phoneLength: 8 },
  { code: "LI", name: "Liechtenstein", dial_code: "+423", phoneLength: 7 },
  { code: "LK", name: "Sri Lanka", dial_code: "+94", phoneLength: 9 },
  { code: "LR", name: "Liberia", dial_code: "+231", phoneLength: [8, 9] },
  { code: "LS", name: "Lesotho", dial_code: "+266", phoneLength: 8 },
  { code: "LT", name: "Lithuania", dial_code: "+370", phoneLength: 8 },
  { code: "LU", name: "Luxembourg", dial_code: "+352", phoneLength: 9 },
  { code: "LV", name: "Latvia", dial_code: "+371", phoneLength: 8 },
  { code: "LY", name: "Libya", dial_code: "+218", phoneLength: 9 },
  { code: "MA", name: "Morocco", dial_code: "+212", phoneLength: 9 },
  { code: "MC", name: "Monaco", dial_code: "+377", phoneLength: 8 },
  { code: "MD", name: "Moldova", dial_code: "+373", phoneLength: 8 },
  { code: "ME", name: "Montenegro", dial_code: "+382", phoneLength: 8 },
  { code: "MG", name: "Madagascar", dial_code: "+261", phoneLength: 7 },
  { code: "MH", name: "Marshall Islands", dial_code: "+692", phoneLength: 7 },
  { code: "MK", name: "North Macedonia", dial_code: "+389", phoneLength: 8 },
  { code: "ML", name: "Mali", dial_code: "+223", phoneLength: 8 },
  { code: "MM", name: "Myanmar", dial_code: "+95", phoneLength: [7, 10] },
  { code: "MN", name: "Mongolia", dial_code: "+976", phoneLength: 8 },
  { code: "MO", name: "Macao", dial_code: "+853", phoneLength: 8 },
  { code: "MV", name: "Maldives", dial_code: "+960", phoneLength: 7 },
  { code: "MW", name: "Malawi", dial_code: "+265", phoneLength: [7, 8, 9] },
  { code: "MX", name: "Mexico", dial_code: "+52", phoneLength: 10 },
  { code: "MY", name: "Malaysia", dial_code: "+60", phoneLength: [9, 10] },
  { code: "MZ", name: "Mozambique", dial_code: "+258", phoneLength: [8, 9] },
  { code: "NA", name: "Namibia", dial_code: "+264", phoneLength: 9 },
  { code: "NC", name: "New Caledonia", dial_code: "+687", phoneLength: 6 },
  { code: "NE", name: "Niger", dial_code: "+227", phoneLength: 8 },
  { code: "NF", name: "Norfolk Island", dial_code: "+672", phoneLength: 6 },
  { code: "NG", name: "Nigeria", dial_code: "+234", phoneLength: 10 },
  { code: "NI", name: "Nicaragua", dial_code: "+505", phoneLength: 8 },
  { code: "NL", name: "Netherlands", dial_code: "+31", phoneLength: 9 },
  { code: "NO", name: "Norway", dial_code: "+47", phoneLength: 8 },
  { code: "NP", name: "Nepal", dial_code: "+977", phoneLength: 10 },
  { code: "NU", name: "Niue", dial_code: "+683", phoneLength: 4 },
  { code: "NZ", name: "New Zealand", dial_code: "+64", phoneLength: [8, 9] },
  { code: "OM", name: "Oman", dial_code: "+968", phoneLength: 8 },
  { code: "PA", name: "Panama", dial_code: "+507", phoneLength: 8 },
  { code: "PE", name: "Peru", dial_code: "+51", phoneLength: 9 },
  { code: "PF", name: "French Polynesia", dial_code: "+689", phoneLength: 8 },
  { code: "PG", name: "Papua New Guinea", dial_code: "+675", phoneLength: 8 },
  { code: "PH", name: "Philippines", dial_code: "+63", phoneLength: 10 },
  { code: "PK", name: "Pakistan", dial_code: "+92", phoneLength: 10 },
  { code: "PL", name: "Poland", dial_code: "+48", phoneLength: 9 },
  { code: "PS", name: "Palestine", dial_code: "+970", phoneLength: 9 },
  { code: "PT", name: "Portugal", dial_code: "+351", phoneLength: 9 },
  { code: "PW", name: "Palau", dial_code: "+680", phoneLength: 7 },
  { code: "PY", name: "Paraguay", dial_code: "+595", phoneLength: 9 },
  { code: "QA", name: "Qatar", dial_code: "+974", phoneLength: 8 },
  { code: "RO", name: "Romania", dial_code: "+40", phoneLength: 10 },
  { code: "RS", name: "Serbia", dial_code: "+381", phoneLength: 9 },
  { code: "RU", name: "Russia", dial_code: "+7", phoneLength: 10 },
  { code: "RW", name: "Rwanda", dial_code: "+250", phoneLength: 9 },
  { code: "SA", name: "Saudi Arabia", dial_code: "+966", phoneLength: 9 },
  { code: "SB", name: "Solomon Islands", dial_code: "+677", phoneLength: 7 },
  { code: "SC", name: "Seychelles", dial_code: "+248", phoneLength: 7 },
  { code: "SD", name: "Sudan", dial_code: "+249", phoneLength: 9 },
  { code: "SE", name: "Sweden", dial_code: "+46", phoneLength: [6, 7, 9] },
  { code: "SG", name: "Singapore", dial_code: "+65", phoneLength: 8 },
  { code: "SI", name: "Slovenia", dial_code: "+386", phoneLength: 9 },
  { code: "SK", name: "Slovakia", dial_code: "+421", phoneLength: 9 },
  { code: "SL", name: "Sierra Leone", dial_code: "+232", phoneLength: 8 },
  { code: "SM", name: "San Marino", dial_code: "+378", phoneLength: 10 },
  { code: "SN", name: "Senegal", dial_code: "+221", phoneLength: 9 },
  { code: "SO", name: "Somalia", dial_code: "+252", phoneLength: [8, 9] },
  { code: "SR", name: "Suriname", dial_code: "+597", phoneLength: [6, 7] },
  { code: "SS", name: "South Sudan", dial_code: "+211", phoneLength: 9 },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    dial_code: "+239",
    phoneLength: 7,
  },
  { code: "SV", name: "El Salvador", dial_code: "+503", phoneLength: 8 },
  { code: "SY", name: "Syria", dial_code: "+963", phoneLength: [7, 9] },
  { code: "TZ", name: "Tanzania", dial_code: "+255", phoneLength: 9 },
  { code: "UA", name: "Ukraine", dial_code: "+380", phoneLength: 9 },
  { code: "UG", name: "Uganda", dial_code: "+256", phoneLength: 9 },
  { code: "US", name: "United States", dial_code: "+1", phoneLength: 10 },
  { code: "UY", name: "Uruguay", dial_code: "+598", phoneLength: 8 },
  { code: "UZ", name: "Uzbekistan", dial_code: "+998", phoneLength: 9 },
  { code: "VA", name: "Vatican City", dial_code: "+379", phoneLength: 10 },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1-784",
    phoneLength: 7,
  },
  { code: "VE", name: "Venezuela", dial_code: "+58", phoneLength: 10 },
  {
    code: "VG",
    name: "British Virgin Islands",
    dial_code: "+1-284",
    phoneLength: 7,
  },
  {
    code: "VI",
    name: "US Virgin Islands",
    dial_code: "+1-340",
    phoneLength: 10,
  },
  { code: "VN", name: "Vietnam", dial_code: "+84", phoneLength: 9 },
  { code: "VU", name: "Vanuatu", dial_code: "+678", phoneLength: 5 },
  { code: "WF", name: "Wallis and Futuna", dial_code: "+681", phoneLength: 6 },
  { code: "WS", name: "Samoa", dial_code: "+685", phoneLength: [5, 6, 7] },
  { code: "YE", name: "Yemen", dial_code: "+967", phoneLength: 9 },
  { code: "ZA", name: "South Africa", dial_code: "+27", phoneLength: 9 },
  { code: "ZM", name: "Zambia", dial_code: "+260", phoneLength: 9 },
  { code: "ZW", name: "Zimbabwe", dial_code: "+263", phoneLength: 9 },
];
